//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GeHosWebApi
{
    using System;
    using System.Collections.Generic;
    using GeHosContract.Contrato;
    
    public partial class Parametros : Entidad
    {
        public string id { get; set; }
        public bool audit { get; set; }
        public string fin_id_default_lg { get; set; }
    }
}
