//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAPI.Models.Entity_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CarreraMatriculada
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CarreraMatriculada()
        {
            this.Titulo = new HashSet<Titulo>();
        }
    
        public int ID { get; set; }
        public string Codigo { get; set; }
        public string ResolucionHabilitante { get; set; }
        public string ResolucionCierre { get; set; }
        public string Nombre { get; set; }
        public Nullable<System.DateTime> FechaAlta { get; set; }
        public byte TipoEstadoProfesionID { get; set; }
    
        public virtual TipoEstadoProfesion TipoEstadoProfesion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Titulo> Titulo { get; set; }
    }
}
