//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAPI.Models.Entity_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class EspecialidadPorCentroDeSalud
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EspecialidadPorCentroDeSalud()
        {
            this.HorariosPorEspecialidadPorCentroDeSalud = new HashSet<HorariosPorEspecialidadPorCentroDeSalud>();
        }
    
        public int ID { get; set; }
        public short CentroDeSaludID { get; set; }
        public short EspecialidadID { get; set; }
        public bool Activo { get; set; }
    
        public virtual CentroDeSalud CentroDeSalud { get; set; }
        public virtual Especialidad Especialidad { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HorariosPorEspecialidadPorCentroDeSalud> HorariosPorEspecialidadPorCentroDeSalud { get; set; }
    }
}
