//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAPI.Models.Entity_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class LineaColectivoPorCentroDeSalud
    {
        public int ID { get; set; }
        public short LineaColectivoID { get; set; }
        public short CentroDeSaludID { get; set; }
        public bool Activo { get; set; }
    
        public virtual CentroDeSalud CentroDeSalud { get; set; }
        public virtual LineaColectivo LineaColectivo { get; set; }
    }
}
