//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAPI.Models.Entity_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProturRegistros
    {
        public int ID { get; set; }
        public long TS { get; set; }
        public int CS { get; set; }
        public int PT { get; set; }
        public System.DateTime DC { get; set; }
        public string PN { get; set; }
        public int SP { get; set; }
        public System.DateTime NP { get; set; }
        public string DP { get; set; }
        public int PO { get; set; }
        public int OS { get; set; }
        public string TP { get; set; }
        public int PD { get; set; }
        public string DO { get; set; }
        public int ET { get; set; }
        public int TT { get; set; }
        public int MT { get; set; }
        public Nullable<int> CT { get; set; }
        public Nullable<int> EI { get; set; }
        public Nullable<int> PE { get; set; }
        public Nullable<int> PC { get; set; }
        public Nullable<System.DateTime> FP { get; set; }
        public Nullable<int> PM { get; set; }
        public int TA { get; set; }
    }
}
