//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAPI.Models.Entity_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class RegistroActualizacionTablas
    {
        public int ID { get; set; }
        public string NombreTabla { get; set; }
        public System.DateTime FechaUltimaActualizacion { get; set; }
    }
}
