//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAPI.Models.Entity_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SolicitudProtur
    {
        public int ID { get; set; }
        public string Nombre { get; set; }
        public short DepId { get; set; }
        public string Telefono1 { get; set; }
        public string Telefono2 { get; set; }
        public string Email { get; set; }
        public string Comentarios { get; set; }
        public System.DateTime Fecha { get; set; }
        public string Direccion { get; set; }
    }
}
