//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GeHosWebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CuentaEscritural
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CuentaEscritural()
        {
            this.Administrador = new HashSet<Administrador>();
        }
    
        public short ID { get; set; }
        public string Codigo { get; set; }
        public string Descripcion { get; set; }
        public short FuenteID { get; set; }
        public Nullable<byte> InstitucionContableID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Administrador> Administrador { get; set; }
        public virtual Fuente Fuente { get; set; }
        public virtual InstitucionContable InstitucionContable { get; set; }
    }
}
