//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GeHosWebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DiagnosticoSubCapitulo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DiagnosticoSubCapitulo()
        {
            this.DiagnosticoPadron = new HashSet<DiagnosticoPadron>();
        }
    
        public short ID { get; set; }
        public string CodigoInicial { get; set; }
        public string CodigoFinal { get; set; }
        public string Descripcion { get; set; }
        public int DiagnosticoCapituloID { get; set; }
    
        public virtual DiagnosticoCapitulo DiagnosticoCapitulo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DiagnosticoPadron> DiagnosticoPadron { get; set; }
    }
}
