//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GeHosWebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DiagnosticoPorTurno
    {
        public long ID { get; set; }
        public long TurnoID { get; set; }
        public int DiagnosticoID { get; set; }
        public System.DateTime FechaAlta { get; set; }
        public int AspNetUsersID { get; set; }
        public bool Activa { get; set; }
    
        public virtual AspNetUsers AspNetUsers { get; set; }
        public virtual Diagnostico Diagnostico { get; set; }
        public virtual Turno Turno { get; set; }
    }
}
