//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GeHosWebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmpleadoEspecialidad
    {
        public int ID { get; set; }
        public int EmpleadoID { get; set; }
        public int EspecialidadID { get; set; }
        public System.DateTime FechaAlta { get; set; }
        public bool Activa { get; set; }
    
        public virtual Empleado Empleado { get; set; }
        public virtual Especialidad Especialidad { get; set; }
    }
}
