//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GeHosWebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmpleadoEspecialidadCentroDeSalud
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EmpleadoEspecialidadCentroDeSalud()
        {
            this.Agenda = new HashSet<Agenda>();
        }
    
        public int ID { get; set; }
        public int EmpleadoID { get; set; }
        public int CentroDeSaludID { get; set; }
        public int EspecialidadID { get; set; }
        public System.DateTime FechaAlta { get; set; }
        public bool Activa { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Agenda> Agenda { get; set; }
        public virtual CentroDeSalud CentroDeSalud { get; set; }
        public virtual Empleado Empleado { get; set; }
        public virtual Especialidad Especialidad { get; set; }
    }
}
