//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GeHosWebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GradosDesignacion
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public GradosDesignacion()
        {
            this.EmpleadoPlantaPermanente = new HashSet<EmpleadoPlantaPermanente>();
        }
    
        public int ID { get; set; }
        public System.DateTime Fecha { get; set; }
        public System.DateTime Horas { get; set; }
        public bool ConAdicional { get; set; }
        public short HorasAdicional { get; set; }
        public string Observaciones { get; set; }
        public string Servicio { get; set; }
        public Nullable<System.DateTime> FechaDesde { get; set; }
        public Nullable<System.DateTime> FechaHasta { get; set; }
        public string Funcion { get; set; }
        public string NumeroRegistro { get; set; }
        public short GradosCategoriaID { get; set; }
        public byte TipoGradosDesignacionID { get; set; }
        public Nullable<long> ResolucionID { get; set; }
        public Nullable<long> DecretoID { get; set; }
    
        public virtual Decreto Decreto { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EmpleadoPlantaPermanente> EmpleadoPlantaPermanente { get; set; }
        public virtual GradosCategoria GradosCategoria { get; set; }
        public virtual Resolucion Resolucion { get; set; }
        public virtual TipoGradosDesignacion TipoGradosDesignacion { get; set; }
    }
}
