//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GeHosWebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GradosCategoria
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public GradosCategoria()
        {
            this.GradosDesignacion = new HashSet<GradosDesignacion>();
        }
    
        public short ID { get; set; }
        public string Nombre { get; set; }
        public short GradosID { get; set; }
        public bool Activa { get; set; }
    
        public virtual Grados Grados { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GradosDesignacion> GradosDesignacion { get; set; }
    }
}
