//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GeHosWebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ObraSocial
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ObraSocial()
        {
            this.Paciente = new HashSet<Paciente>();
        }
    
        public int ID { get; set; }
        public int Codigo { get; set; }
        public string Denominacion { get; set; }
        public string Sigla { get; set; }
        public string Domicilio { get; set; }
        public short CodigoPostal { get; set; }
        public int ProvinciaID { get; set; }
        public string Telefono { get; set; }
        public string Mail { get; set; }
        public string Web { get; set; }
        public bool EsPrepaga { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Paciente> Paciente { get; set; }
    }
}
