//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GeHosWebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Paciente
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Paciente()
        {
            this.Turno = new HashSet<Turno>();
        }
    
        public int ID { get; set; }
        public int PersonaID { get; set; }
        public Nullable<int> ObraSocialID { get; set; }
        public Nullable<bool> EsDonanteDeOrganos { get; set; }
        public Nullable<bool> Hospitalizado { get; set; }
        public Nullable<int> GrupoSanguineoID { get; set; }
        public Nullable<int> CentroDeSaludID { get; set; }
        public string NumeroHistoriaClinica { get; set; }
    
        public virtual CentroDeSalud CentroDeSalud { get; set; }
        public virtual GrupoSanguineo GrupoSanguineo { get; set; }
        public virtual ObraSocial ObraSocial { get; set; }
        public virtual Persona Persona { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Turno> Turno { get; set; }
    }
}
