//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GeHosWebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Persona
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Persona()
        {
            this.Empleado = new HashSet<Empleado>();
            this.Paciente = new HashSet<Paciente>();
        }
    
        public int ID { get; set; }
        public string Apellido { get; set; }
        public string Nombre { get; set; }
        public byte TipodniID { get; set; }
        public Nullable<int> NroDocumento { get; set; }
        public Nullable<bool> DocumentoPropio { get; set; }
        public Nullable<byte> EstadoCivilID { get; set; }
        public Nullable<byte> SexoID { get; set; }
        public Nullable<System.DateTime> FechaNacimiento { get; set; }
        public Nullable<bool> PuebloIndigena { get; set; }
        public Nullable<int> LocalidadID { get; set; }
        public string CodigoPostal { get; set; }
        public string DomicilioCalle { get; set; }
        public string DomicilioNumero { get; set; }
        public string DomicilioManzana { get; set; }
        public string DomicilioPiso { get; set; }
        public string DomicilioDepto { get; set; }
        public string CalleReferencia1 { get; set; }
        public string CalleReferencia2 { get; set; }
        public Nullable<int> BarrioID { get; set; }
        public string TelefonoFijo { get; set; }
        public string TelefonoCelular { get; set; }
        public string Email { get; set; }
        public Nullable<byte> LenguaID { get; set; }
        public Nullable<byte> TribuID { get; set; }
        public Nullable<byte> EtniaID { get; set; }
        public Nullable<int> LocalidadNacimientoID { get; set; }
        public Nullable<int> NacionalidadID { get; set; }
        public Nullable<bool> Indocumentado { get; set; }
        public string CUIL { get; set; }
        public Nullable<byte> GrupoSanguineoID { get; set; }
        public Nullable<byte> TipoCoberturaSocialID { get; set; }
        public Nullable<int> CoberturaSocialID { get; set; }
        public Nullable<System.DateTime> CoberturaSocialDesde { get; set; }
        public string ScoreDeRiesgo { get; set; }
        public string NroHC { get; set; }
        public Nullable<byte> ZonaDeSaludID { get; set; }
        public string Alfabeta { get; set; }
        public Nullable<byte> EstudiosID { get; set; }
        public string AñoMayorNivelDeEstudio { get; set; }
    
        public virtual Barrio Barrio { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Empleado> Empleado { get; set; }
        public virtual EstadoCivil EstadoCivil { get; set; }
        public virtual Etnia Etnia { get; set; }
        public virtual GrupoSanguineo GrupoSanguineo { get; set; }
        public virtual Localidad Localidad { get; set; }
        public virtual Localidad Localidad1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Paciente> Paciente { get; set; }
        public virtual Sexo Sexo { get; set; }
        public virtual TipoDNI TipoDNI { get; set; }
    }
}
