//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GeHosWebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Practica
    {
        public long ID { get; set; }
        public string Codigo { get; set; }
        public string Descripcion { get; set; }
        public decimal Costo { get; set; }
        public Nullable<int> NomencladorID { get; set; }
        public decimal Uop { get; set; }
        public bool Activa { get; set; }
    
        public virtual Nomenclador Nomenclador { get; set; }
    }
}
