//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GeHosWebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Turno
    {
        public long ID { get; set; }
        public Nullable<long> PacienteID { get; set; }
        public int AgendaHorarioID { get; set; }
        public System.DateTime FechaTurno { get; set; }
        public byte TurnoEstadoID { get; set; }
        public byte TurnoEstadoAdmisionID { get; set; }
        public Nullable<bool> EsSobreturno { get; set; }
        public Nullable<System.DateTime> FechaAdmision { get; set; }
        public Nullable<System.DateTime> FechaInicioAtencion { get; set; }
        public Nullable<System.DateTime> FechaFinAtencion { get; set; }
        public Nullable<bool> EsPrioritario { get; set; }
        public Nullable<int> BloqueoMasivoID { get; set; }
        public Nullable<bool> EsProgramado { get; set; }
    
        public virtual AgendaHorario AgendaHorario { get; set; }
        public virtual Paciente Paciente { get; set; }
        public virtual TurnoEstado TurnoEstado { get; set; }
        public virtual TurnoEstadoAdmision TurnoEstadoAdmision { get; set; }
    }
}
