//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MSP_RegProf.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Horarios
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Horarios()
        {
            this.HorariosPorEspecialidadPorCentroDeSalud = new HashSet<HorariosPorEspecialidadPorCentroDeSalud>();
            this.HorariosPorEspecialidadPorCentroDeSalud1 = new HashSet<HorariosPorEspecialidadPorCentroDeSalud>();
        }
    
        public short ID { get; set; }
        public string Hora { get; set; }
        public bool Activo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HorariosPorEspecialidadPorCentroDeSalud> HorariosPorEspecialidadPorCentroDeSalud { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HorariosPorEspecialidadPorCentroDeSalud> HorariosPorEspecialidadPorCentroDeSalud1 { get; set; }
    }
}
