//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MSP.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class Certificado
    {
        public int ID { get; set; }
        public int IdEstablecimiento { get; set; }

        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:dd/MM/yyyy}")]
        [DisplayName("Fecha Emision")]
        public System.DateTime FechaEmision { get; set; }

        [DisplayFormat(ApplyFormatInEditMode = true,DataFormatString = "{0:dd/MM/yyyy}")]
        [DisplayName("Desde")]
        public System.DateTime FechaDesde { get; set; }

        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:dd/MM/yyyy}")]
        [DisplayName("Hasta")]
        public System.DateTime FechaHasta { get; set; }

        [Required(AllowEmptyStrings = false)]
        public string NroExpediente { get; set; }
        public int IdCertificadoTipo { get; set; }
        public string IdUsuarioEmite { get; set; }

        public virtual AspNetUsers AspNetUsers { get; set; }
        public virtual CertificadoEstablecimiento CertificadoEstablecimiento { get; set; }
        public virtual TipoCertificado TipoCertificado { get; set; }
    }
}
