//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MSP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TipoCertificadoEstablecimiento
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TipoCertificadoEstablecimiento()
        {
            this.CertificadoEstablecimiento = new HashSet<CertificadoEstablecimiento>();
            this.CertificadoEstablecimentoItem = new HashSet<CertificadoEstablecimentoItem>();
        }
    
        public int ID { get; set; }
        public string Denominacion { get; set; }
        public int IdTipoCertificado { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CertificadoEstablecimiento> CertificadoEstablecimiento { get; set; }
        public virtual TipoCertificado TipoCertificado { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CertificadoEstablecimentoItem> CertificadoEstablecimentoItem { get; set; }
    }
}
