//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MSP_Certificados.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CertificadoEstablecimiento
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CertificadoEstablecimiento()
        {
            this.Certificado = new HashSet<Certificado>();
        }
    
        public int ID { get; set; }
        public int IdTipoEstablecimiento { get; set; }
        public string Denominacion { get; set; }
        public System.DateTime FechaAlta { get; set; }
        public string IdUsuarioAlta { get; set; }
        public bool Activo { get; set; }
        public string Domicilio { get; set; }
        public string DomicilioDepto { get; set; }
        public string Firma { get; set; }
        public string FirmaDni { get; set; }
        public string FirmaDireccion { get; set; }
        public string FirmaDepto { get; set; }
    
        public virtual AspNetUsers AspNetUsers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Certificado> Certificado { get; set; }
        public virtual TipoCertificadoEstablecimiento TipoCertificadoEstablecimiento { get; set; }
    }
}
