//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MSP_Certificados.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CertificadoEstablecimentoItem
    {
        public int ID { get; set; }
        public string Descripcion { get; set; }
        public int IdTipoEstablecimiento { get; set; }
    
        public virtual TipoCertificadoEstablecimiento TipoCertificadoEstablecimiento { get; set; }
    }
}
