//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GeHosData.DB
{
    using GeHosContract.Contrato;
    using System;
    using System.Collections.Generic;

    public partial class catAgenda : Entidad
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public catAgenda()
        {
            this.catAgendaHorario = new HashSet<catAgendaHorario>();
        }
    
        public int agId { get; set; }
        public Nullable<int> perId { get; set; }
        public Nullable<int> conId { get; set; }
        public int csId { get; set; }
        public short espId { get; set; }
        public byte agDuracion { get; set; }
        public byte agSobreturnos { get; set; }
        public bool agActivo { get; set; }
        public byte agEstado { get; set; }
    
        public virtual catCentroDeSalud catCentroDeSalud { get; set; }
        public virtual catEspecialidad catEspecialidad { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<catAgendaHorario> catAgendaHorario { get; set; }
    }
}
