//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GeHosData.DB
{
    using GeHosContract.Contrato;
    using System;
    using System.Collections.Generic;

    public partial class catAgendaHorario : Entidad
    {
        public int aghId { get; set; }
        public string aghDiaSemana { get; set; }
        public string aghHoraInicio { get; set; }
        public string aghMinutoInicio { get; set; }
        public string aghHoraFin { get; set; }
        public string aghMinutoFin { get; set; }
        public System.DateTime aghVigenciaDesde { get; set; }
        public System.DateTime aghVigenciaHasta { get; set; }
        public int agId { get; set; }
        public bool aghActivo { get; set; }
        public Nullable<int> aghCantTurnos { get; set; }
        public Nullable<int> aghSobreturnos { get; set; }
        public byte aghTipoAgenda { get; set; }
    
        public virtual catAgenda catAgenda { get; set; }
    }
}
