//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GeHosData.DB
{
    using GeHosContract.Contrato;
    using System;
    using System.Collections.Generic;

    public partial class catAlergia : Entidad
    {
        public short alId { get; set; }
        public string alNombre { get; set; }
        public bool alEsMedicamento { get; set; }
    }
}
