//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GeHosData.DB
{
    using GeHosContract.Contrato;
    using System;
    using System.Collections.Generic;

    public partial class catCentroDeSalud : Entidad
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public catCentroDeSalud()
        {
            this.catAgenda = new HashSet<catAgenda>();
        }
    
        public int csId { get; set; }
        public string csCodigo { get; set; }
        public string csNombre { get; set; }
        public Nullable<short> depId { get; set; }
        public string csLatitud { get; set; }
        public string csDirector { get; set; }
        public string csTipologia { get; set; }
        public string csTelefono { get; set; }
        public string csLongitud { get; set; }
        public string csDomicilio { get; set; }
        public Nullable<int> csPublico { get; set; }
        public Nullable<int> cszId { get; set; }
        public string CodBioestadistica { get; set; }
        public string CodRemediar { get; set; }
        public Nullable<int> CantVivienda { get; set; }
        public Nullable<int> CantVaron { get; set; }
        public Nullable<int> CantMujeres { get; set; }
        public Nullable<int> Total { get; set; }
        public Nullable<short> admId { get; set; }
        public byte[] csPassword { get; set; }
        public Nullable<bool> csRequiereHc { get; set; }
        public Nullable<bool> csCargaDatosTurnosPasado { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<catAgenda> catAgenda { get; set; }
    }
}
