//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GeHosData.DB
{
    using GeHosContract.Contrato;
    using System;
    using System.Collections.Generic;

    public partial class catEspecialidad : Entidad
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public catEspecialidad()
        {
            this.catAgenda = new HashSet<catAgenda>();
        }
    
        public short espId { get; set; }
        public string espNombre { get; set; }
        public Nullable<short> espIdPadre { get; set; }
        public string espCodigo { get; set; }
        public string espDescripcionPlanilla { get; set; }
        public string espAbreviatura { get; set; }
        public int espIdMHO { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<catAgenda> catAgenda { get; set; }
    }
}
