//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GeHosData.DB
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<catAgenda> catAgenda { get; set; }
        public virtual DbSet<catAgendaHorario> catAgendaHorario { get; set; }
        public virtual DbSet<catAlergia> catAlergia { get; set; }
        public virtual DbSet<catCentroDeSalud> catCentroDeSalud { get; set; }
        public virtual DbSet<catEspecialidad> catEspecialidad { get; set; }
    }
}
